name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Rust CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Format (rustfmt)
        run: cargo fmt --all -- --check

      - name: Lint (clippy)
        run: cargo clippy --workspace --all-targets --all-features -D warnings

      - name: Test
        run: cargo test --workspace --all-features --locked

